import type { ReactNode } from "react";

import Head from "next/head";
import { Box, Container, Flex } from "@chakra-ui/react";

import ColorModeSwitcher from "@/components/ColorModeSwitcher";

type PageProps = {
  children?: ReactNode;
  title?: string;
};

function Page({ children, title = "This is the default title" }: PageProps) {
  return (
    <Box backgroundColor="teal.50" width="100vw" height="100vh">
      <Head>
        <title>{title}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="header">
        <Flex p={4} justifyContent="end" alignItems="center" mb={8}>
          <ColorModeSwitcher />
        </Flex>
      </Box>

      <Container maxWidth="8xl">{children}</Container>
    </Box>
  );
}

export default Page;
